---
title: Ancient Truth Investigators
timezone: America/New_York
collections:
  artifacts:
    title: Artifacts
    output: true
  elements:
    title: Elements
    output: true
  entries:
    title: Entries
    output: true
  posts:
    title: Posts
    output: true
  product-colors:
    title: Product-Colors
    output: true
  products:
    title: Products
    output: true
  sightings:
    title: Sightings
    output: true
    future: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
  home-images:
    title: home-images
    output: true
defaults:
- scope:
    path: ''
    type: entries
  values:
    permalink: "/log-book/:title/"
    entry-number: ''
    summary: ''
    image: "/uploads/02-347f2d.jpg"
    featured-video: ''
    layout: log-book
    author:
      image: "/uploads/RachelRader_avatar.jpg"
      name: Ráchel Räder, C.I.
      title: 'Chief Investigator,         Ancient Truth Investigators'
- scope:
    path: ''
    type: team
  values:
    team-title: ''
    website: ''
    image: ''
- scope:
    path: ''
    type: artifacts
  values:
    images:
    - ''
    - ''
    catalogue-number:
    size:
    material:
    creation-date:
    layout: artifact
- scope:
    path: ''
    type: products
  values:
    layout: shop-item
    visible-title: ''
    elements:
    product-colors:
    permalink: "/shop/:title/"
    price: 666.66
    sku: ati
    weight: 0.0
    width: ''
    height: ''
    materials: Bronze, Glass, Cubic Zirconia
    product-images:
    -
    -
    -
    -
    -
- scope:
    path: ''
    type: sightings
  values:
    layout: sightings
    start-date:
    end-date:
    time:
    external-link:
    location:
      name:
      address:
      latitude:
      longitude:
- scope:
    path: ''
    type: team
  values:
    layout: team
    image:
    team-title:
    external-link:
    instagram:
    twitter:
    facebook:
- scope:
    path: ''
    type: product-colors
  values:
    color: ''
- scope:
    path: ''
    type: home-images
  values:
    image: ''
    texture-image: ''
snipcart_api_key: YjM2NGJjN2ItZjQwZC00M2ZjLTgxOTAtNmM1ZDA3MmE3NDRlNjM2MzA0MDkwMDA4NjU4NTAz
logo: "/includes/svg/ATI_b.svg"
gems:
- jekyll-sitemap
email: ibelieve@ancienttruthinvestigators.com
description: The Ancient Truth Investigators are scientists, writers, makers, creatives
  and healers. Collectively, they strive to find ways to aid Humanity's growth towards
  a more evolved bond between ourselves and the planet.
url:
twitter_username: A_T_I_lab
github_username: DanRader
google-analytics:
permalink: pretty
