---
title: Ancient Truth Investigators
timezone: America/New_York
collections:
  artifacts:
    title: Artifacts
    output: true
  elements:
    title: Elements
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  sightings:
    title: Sightings
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: products
  values:
    layout: shop-item
    permalink: "/products/:title/"
    price: 666.66
    sku: ati
    image: ''
    weight: 0.0
    width: 2”
    height: 3/8"
    materials: Bronze, Glass, Cubic Zirconia
    product-images:
    - http://3milliondogs.com/blog-assets-two/2014/08/corgicute.jpg
    - http://stories.barkpost.com/wp-content/uploads/2015/01/corgi2.jpg
    - https://i.ytimg.com/vi/Tdxqr20jS68/maxresdefault.jpg
    - http://www.dogbreedslist.info/uploads/allimg/dog-pictures/Cardigan-Welsh-Corgi-3.jpg
    - http://buzzsharer.com/wp-content/uploads/2015/11/running-corgi-snow-cute.jpg
- scope:
    path: ''
    type: sightings
  values:
    layout: sightings
    end-date: 
    location: 
    external-link: 
snipcart_api_key: YjM2NGJjN2ItZjQwZC00M2ZjLTgxOTAtNmM1ZDA3MmE3NDRlNjM2MzA0MDkwMDA4NjU4NTAz
logo: "/includes/svg/ATI_b.svg"
gems:
- jekyll-sitemap
email: ibelieve@ancienttruthinvestigators.com
description: The Ancient Truth Investigators are scientists, writers, makers, creatives
  and healers. Collectively, they strive to find ways to aid Humanity's growth towards
  a more evolved bond between ourselves and the planet.
url: 
twitter_username: A_T_I_lab
github_username: DanRader
google-analytics: 
permalink: pretty
